import Card from '../components/ui/Card'
import PriceTile from '../components/ui/PriceTile'
import Slider from '../components/ui/Slider'
import Toggle from '../components/ui/Toggle'
import { calculateCO2 } from '../utils/budgetCalc'

export default function TransportSection({ trip, destination, onUpdate }) {
 const mode = trip.transport.mode
 const setTransport=(patch)=>onUpdate({ transport:{ ...trip.transport, ...patch } })
 const co2 = calculateCO2(mode, trip.transport.vehicles || 1, destination?.distance || 800, trip.people.total)
 return <Card><h3 className='section-title'>Transport</h3><div className='flex gap-2 overflow-auto'>{['car','flight','train','bus','other'].map((m)=><button key={m} className={`tab-btn ${mode===m?'active':''}`} onClick={()=>setTransport({ mode:m })}>{m.toUpperCase()}</button>)}</div>
 {mode==='flight' && <div className='mt-3 grid gap-2 sm:grid-cols-3'><PriceTile title='Budget' subtitle='LCC carriers' price={destination?.flight?.[0]||4500} selected={trip.transport.tier==='budget'} onClick={()=>setTransport({ tier:'budget' })}/><PriceTile title='Standard' subtitle='Balanced fares' price={destination?.flight?.[1]||7800} selected={trip.transport.tier==='standard'} onClick={()=>setTransport({ tier:'standard' })}/><PriceTile title='Peak / Last min' subtitle='Higher flexibility' price={destination?.flight?.[2]||14500} selected={trip.transport.tier==='peak'} onClick={()=>setTransport({ tier:'peak' })}/></div>}
 {mode==='car' && <div className='mt-3 grid gap-3 sm:grid-cols-2'><label><span className='text-xs text-text-secondary'>Fuel price</span><input className='input-base' type='number' value={trip.transport.fuelPrice||103} onChange={(e)=>setTransport({ fuelPrice:Number(e.target.value) })}/></label><label><span className='text-xs text-text-secondary'>Mileage km/l</span><input className='input-base' type='number' value={trip.transport.kmpl||15} onChange={(e)=>setTransport({ kmpl:Number(e.target.value) })}/></label><Slider label='Vehicles' min={1} max={3} value={trip.transport.vehicles||1} onChange={(v)=>setTransport({ vehicles:v })}/><Toggle label='Hire driver' checked={!!trip.transport.hireDriver} onChange={(v)=>setTransport({ hireDriver:v })} /></div>}
 {mode==='train' && <div className='mt-3 flex gap-2'><button className={`tab-btn ${trip.transport.classTier==='sleeper'?'active':''}`} onClick={()=>setTransport({ classTier:'sleeper' })}>Sleeper</button><button className={`tab-btn ${trip.transport.classTier==='3ac'?'active':''}`} onClick={()=>setTransport({ classTier:'3ac' })}>3AC</button><button className={`tab-btn ${trip.transport.classTier==='2ac'?'active':''}`} onClick={()=>setTransport({ classTier:'2ac' })}>2AC</button><Toggle label='Tatkal' checked={!!trip.transport.tatkal} onChange={(v)=>setTransport({ tatkal:v })}/></div>}
 {mode==='bus' && <div className='mt-3 flex gap-2'><button className={`tab-btn ${trip.transport.busTier==='ordinary'?'active':''}`} onClick={()=>setTransport({ busTier:'ordinary' })}>Ordinary</button><button className={`tab-btn ${trip.transport.busTier==='ac'?'active':''}`} onClick={()=>setTransport({ busTier:'ac' })}>AC</button><button className={`tab-btn ${trip.transport.busTier==='luxury'?'active':''}`} onClick={()=>setTransport({ busTier:'luxury' })}>Luxury</button></div>}
 {mode==='other' && <div className='mt-3 grid gap-2 sm:grid-cols-2'><input className='input-base' placeholder='Mode name' value={trip.transport.otherName||''} onChange={(e)=>setTransport({ otherName:e.target.value })}/><input className='input-base' type='number' placeholder='Amount' value={trip.transport.amount||0} onChange={(e)=>setTransport({ amount:Number(e.target.value) })}/></div>}
 <p className='mt-3 text-xs text-text-secondary'>Estimated CO2: <strong>{Math.round(co2)} kg</strong></p></Card>
}
